spring:
  config:
    import: optional:configserver:http://localhost:8888/
    label: user-write-service
  cloud:
    vault:
      generic:
        enabled: true
        profile-separator: '/'
        default-context: user-write-service
  application:
    name: user-write-service
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 0